apiVersion: v1
data:
  application-routes.yml: |-
    spring:
        # profile: routes
        cloud:
            gateway:
                routes:
                - id: no_logging_route
                  uri: https://httpbin.org/
                  predicates:
                  - Path=/get
                  filters:
                  - AddRequestHeader=X-Request-red, blue
                  - Logging=audit för informationsmängd _get_, true, true


                - id: auditable_route_1_coarse_granularity
                  uri: https://httpbin.org/
                  predicates:
                  - Path=/anything/{segment}
                  filters:
                  - AddRequestHeader=X-Request-red, blue
                  - SecurityAbc=säkerhet för _GET_ operation på informationsmängd _anything_, true, true
                  - SetRequestAuthHeader=Authorization, true, true
                  - Logging=audit för informationsmängd _anything_, true, true

                # https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-path-route-predicate-factory
                - id: auditable_route_2_fine_granularity
                  uri: https://httpbin.org/
                  predicates:
                  - Path=/uuid
                  - Method=GET
                  filters:
                  - SecurityAbc=säkerhet för _GET_ operation på informationsmängd _uuid_, true, true
                  - SetRequestAuthHeader=Authorization, true, true
                  - Logging=audit för _GET_ operation på informationsmäng _uuid_, true, true

                - id: auditable_route_3_with_circuit_breaker
                  uri: https://httpbin.org/
                  predicates:
                  - Path=/delay/{segment}
                  - Method=GET
                  filters:
                  - SecurityAbc=säkerhet för _GET_ operation på informationsmängd _delay_, true, true
                  - SetRequestAuthHeader=Authorization, true, true
                  - Logging=audit för _GET_ operation på informationsmäng _delay_, true, true
                  - name: CircuitBreaker
                    args:
                        name: myCircuitBreaker
                        # fallbackUri: forward:/inCaseOfFailureUseThis
                        fallbackUri: forward:/delay/0

                - id: auditable_route_4_body_logging
                  uri: https://httpbin.org/
                  predicates:
                  - Path=/delay/{segment}
                  - Method=POST
                  filters:
                  - SecurityAbc=säkerhet för _POST_ operation på informationsmängd _delay_, true, true
                  - SetRequestAuthHeader=Authorization, true, true
                  - Logging=audit för _POST_ operation på informationsmäng _delay_, true, true
kind: ConfigMap
metadata:
  labels:
    app: api-gw-tenant1
  name: api-gw-tenant1
