apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: api-gw-subtenant-1
  name: api-gw-subtenant-1
spec:
  host: api-gw-subtenant-1-subtenant-1-namespace-2.apps-crc.testing
  port:
    targetPort: 8080
  subdomain: ""
  to:
    kind: Service
    name: api-gw-subtenant-1
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
